### ISSUE TITLE
The prediction results using your repo and original darknet alexeyab repo is different. is there any critical reason for that? how can I solve it? 

### ISSUE THREAD

**Issue by Fetulhak** [philipperemy/python-darknet-yolo-v4#5]

**Comment by philipperemy** [comment]
@Fetulhak absolutely no reason for that. Try to check the parameters that the official repo uses.
Especially that one: https://github.com/philipperemy/python-darknet-yolo-v4/blob/db68ab2d7e244d5f4b8588c5e99b44ecf163b510/yolov4/darknet.py#L257.

Also if you run it on the CPU and on the GPU, you might see some differences. But that's caused by darknet and not this lib.

Let me know
